{{- if eq .Values.production false -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  labels:
    app: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: localstack
    spec:
      volumes:
        - name: localstack-storage
          emptyDir: {}
      containers:
        - name: localstack
          image: localstack/localstack
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 4566
              protocol: TCP
          env:
            - name: SERVICES
              value: "s3,cloudformation,sts"
            - name: DEFAULT_REGION
              value: "ap-southeast-2"
          volumeMounts:
            - mountPath: "/localstack/data"
              name: localstack-storage
          livenessProbe:
            httpGet:
              path: /health
              port: 4566
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 4566
            initialDelaySeconds: 30
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: localstack-service
spec:
  selector:
    app: localstack
  ports:
    - protocol: TCP
      port: 4566
      targetPort: 4566
{{- end -}}