{{- if eq .Values.production false -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: localstack-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: s3.localstack.{{ .Values.subdomain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: localstack-service
            port:
              number: 4566
{{- end -}}