name: generate plantuml
# Restrict it to run only when top-level files in /uml are modified but not on
# the main branch to avoid commits being made directly against main.
on:
  push:
    paths:
      - "uml/*"
    branches-ignore:
      - "main"

jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: generate plantuml
        id: plantuml
        uses: grassedge/generate-plantuml-action@v1.5
        with:
          path: .generated-diagrams
          message: "Render PlantUML files"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}